name: 跨平台构建Bilibili工具

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            platform: windows
            arch: x64
            executable_suffix: .exe
            artifact_name: bilibili-tools-windows-x64
          - os: macos-latest
            platform: macos
            arch: x64
            executable_suffix: ""
            artifact_name: bilibili-tools-macos-x644
          - os: ubuntu-latest
            platform: linux
            arch: x64
            executable_suffix: ""
            artifact_name: bilibili-tools-linux-x64

    runs-on: ${{ matrix.os }}

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: 设置环境变量
      run: |
        echo "PYTHONIOENCODING=utf-8" >> $GITHUB_ENV
        echo "PYTHONUTF8=1" >> $GITHUB_ENV
      shell: bash


    - name: 安装Linux系统依赖
      if: matrix.platform == 'linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libxcb-xinerama0 \
          libxcb-cursor0 \
          libxkbcommon-x11-0 \
          libxcb-icccm4 \
          libxcb-image0 \
          libxcb-keysyms1 \
          libxcb-randr0 \
          libxcb-render-util0 \
          libxcb-shape0 \
          libgl1-mesa-dri \
          libegl1 \
          libxrandr2 \
          libxss1 \
          libxcomposite1 \
          libxdamage1 \
          libxtst6 \
          libdrm2 \
          libxext6 \
          libxfixes3 \
          libasound2t64 \
          libpulse0 \
          libglib2.0-0 \
          libfontconfig1 \
          libfreetype6 \
          libx11-6 \
          libxcb1 \
          libxi6 \
          libxrender1

    - name: macOS环境配置
      if: matrix.platform == 'macos'
      run: |
        brew update || true
        echo "macOS环境准备完成"

    - name: Windows环境配置
      if: matrix.platform == 'windows'
      run: |
        echo "Windows环境准备完成"
        chcp 65001
      shell: cmd

    - name: 升级pip和安装基础工具
      run: |
        python -m pip install --upgrade pip setuptools wheel

    - name: 安装PyInstaller
      run: |
        pip install pyinstaller

    - name: 安装项目依赖
      run: |
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi
        
        # 确保核心依赖正确安装
        pip install PyQt6
        pip install qasync
        pip install aiohttp
        pip install requests
        pip install curl-cffi
        pip install tqdm
        pip install qrcode[pil]
        pip install Pillow
      shell: bash

    - name: 验证关键依赖
      run: |
        python -c "from PyQt6 import QtCore; print('PyQt6 Qt version:', QtCore.QT_VERSION_STR)"
        python -c "import curl_cffi; print('curl_cffi imported successfully')"
        python -c "import qrcode; print('qrcode imported successfully')"
        python -c "import PIL; print('PIL version:', PIL.__version__)"
      shell: bash

    - name: 检查项目结构
      run: |
        echo "=== 项目根目录 ==="
        ls -la
        echo "=== src目录 ==="
        ls -la src/ || echo "src目录不存在"
        echo "=== assets目录 ==="
        ls -la assets/ || echo "assets目录不存在"
        echo "=== 检查图标文件 ==="
        ls -la assets/1.png || echo "图标文件不存在"
      shell: bash

    - name: 创建跨平台spec文件
      run: |
        cat > "cross-platform.spec" << 'EOF'
        # -*- mode: python ; coding: utf-8 -*-
        import sys
        import os

        block_cipher = None

        # 获取当前平台
        is_windows = sys.platform.startswith('win')
        is_macos = sys.platform == 'darwin'
        is_linux = sys.platform.startswith('linux')

        # 设置平台特定的配置
        if is_windows:
            exe_name = 'Bilibili-Tool'
            console_mode = False
            icon_path = 'assets/1.png' if os.path.exists('assets/1.png') else None
        elif is_macos:
            exe_name = 'Bilibili-Tool'
            console_mode = False
            icon_path = 'assets/1.png' if os.path.exists('assets/1.png') else None
        else:  # Linux
            exe_name = 'Bilibili-Tool'
            console_mode = False
            icon_path = None

        a = Analysis(
            ['main.py'],
            pathex=[],
            binaries=[],
            datas=[
                ('assets', 'assets'),
                ('src', 'src'),
            ],
            hiddenimports=[
                'PyQt6.QtCore',
                'PyQt6.QtGui',
                'PyQt6.QtWidgets',
                'PyQt6.sip',
                'qasync',
                'asyncio',
                'aiohttp',
                'aiohttp.client',
                'aiohttp.connector',
                'sqlite3',
                'requests',
                'curl_cffi',
                'curl_cffi.requests',
                'json',
                'pickle',
                'logging',
                'tqdm',
                'qrcode',
                'PIL',
                'PIL.Image',
                'src.api.api_service',
                'src.api.account_manager',
                'src.api.aicu',
                'src.api.comment',
                'src.api.danmu',
                'src.api.drissionpage_service',
                'src.api.notify',
                'src.api.qr_code',
                'src.database.manager',
                'src.database.models',
                'src.database.sync',
                'src.database.incremental',
                'src.screens.tool_selection_screen',
                'src.screens.Comment_Clean_Screen',
                'src.screens.message_manager_screen',
                'src.screens.comment_stats_screen',
                'src.screens.comment_detail_screen',
                'src.screens.record_comdanmus_screen',
                'src.screens.unlike_screen',
                'src.screens.unfollow_screen',
                'src.screens.cookie_screen',
                'src.screens.qrcode_screen',
                'src.style',
                'src.types',
                'src.utils',
            ],
            hookspath=[],
            hooksconfig={},
            runtime_hooks=[],
            excludes=[
                'PyQt5',
                'tkinter',
                'matplotlib',
                'numpy',
                'pandas',
                'scipy',
                'jupyter',
                'IPython',
                'notebook',
            ],
            win_no_prefer_redirects=False,
            win_private_assemblies=False,
            cipher=block_cipher,
            noarchive=False,
        )

        pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

        exe = EXE(
            pyz,
            a.scripts,
            a.binaries,
            a.zipfiles,
            a.datas,
            [],
            name=exe_name,
            debug=False,
            bootloader_ignore_signals=False,
            strip=False,
            upx=True,
            upx_exclude=[],
            runtime_tmpdir=None,
            console=console_mode,
            disable_windowed_traceback=False,
            argv_emulation=False,
            target_arch=None,
            codesign_identity=None,
            entitlements_file=None,
            icon=icon_path,
        )

        # macOS应用包
        if is_macos:
            app = BUNDLE(
                exe,
                name='Bilibili-Tool.app',
                icon=icon_path,
                bundle_identifier='com.bilibili.tools',
                info_plist={
                    'NSHighResolutionCapable': 'True',
                    'NSRequiresAquaSystemAppearance': 'False',
                }
            )
        EOF
      shell: bash

    - name: 使用PyInstaller构建
      run: |
        # 设置环境变量
        export PYTHONIOENCODING=utf-8
        export PYTHONUTF8=1
        
        # Linux下设置显示环境
        if [ "${{ matrix.platform }}" = "linux" ]; then
          export QT_QPA_PLATFORM=offscreen
          export DISPLAY=:99
        fi
        
        # 执行构建
        pyinstaller cross-platform.spec --noconfirm --clean
        
        # 检查构建结果
        echo "构建完成"
        ls -la dist/
      shell: bash

    - name: 重命名构建产物
      run: |
        cd dist
        
        if [ "${{ matrix.platform }}" = "windows" ]; then
          if [ -f "Bilibili小工具.exe" ]; then
            mv "Bilibili小工具.exe" "BilibiliTools-Windows-x64.exe" 
          fi
        elif [ "${{ matrix.platform }}" = "macos" ]; then
          if [ -d "Bilibili小工具.app" ]; then
            mv "Bilibili小工具.app" "BilibiliTools.app" 
            hdiutil create -volname "BilibiliTools" -srcfolder "BilibiliTools.app" -ov -format UDZO "BilibiliTools-macOS-x64.dmg"
          fi
          if [ -f "Bilibili小工具" ]; then
            mv "Bilibili小工具" "BilibiliTools-macOS-x64"  
          fi
        else  # Linux
          if [ -f "Bilibili小工具" ]; then
            mv "Bilibili小工具" "BilibiliTools-Linux-x64" 
            chmod +x "BilibiliTools-Linux-x64"
          fi
        fi
        echo "=== 重命名后的文件 ==="
        ls -la
      shell: bash

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: |
          dist/BilibiliTools-Windows-x64.exe
          dist/BilibiliTools-macOS-x64
          dist/BilibiliTools-macOS-x64.dmg
          dist/BilibiliTools.app/
          dist/BilibiliTools-Linux-x64
        retention-days: 30

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: 下载所有构建产物
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: 创建发布
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/**/*
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}